language: python
python:
  - "3.3"
  - "2.7"
install:
  - "pip install -r test_requirements.txt"
  - "python setup.py install"
script:
  - "python setup.py test"
  - "behave -s"
  - "pip install polycircles"
  - "yes | pip uninstall polycircles"
